site_name: Boosting

extra_javascript:
  - /js/extra.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - Home: index.md
  - DecisionTree: decisiontree.md
  - Adaboost: adaboost.md
  - GBM: gbm.md
  - XGBoost: xgboost.md
  - LightGBM: lightgbm.md
  - CatBoost: catboost.md
  - RandomForest: randomforest.md